/* -*- coding: utf-8 -*-
 * Generated by protobuf_distutils.generate_py_protobufs.
 */

#define PY_SSIZE_T_CLEAN
#include <Python.h>

static PyMethodDef methods[] = {
    /* no methods */
    {NULL, NULL, 0, NULL}
};

/*
 * This is a do-nothing module for purposes of linking generated C++ protobuf
 * descriptors.
 */
static struct PyModuleDef _descriptors_module = {
    PyModuleDef_HEAD_INIT,
    /* module name */ "_descriptors",
    /* module doc  */ NULL,
    /* state size  */ -1,
    /* methods     */ methods
};

PyMODINIT_FUNC PyInit__descriptors(void) {
  return PyModule_Create(&_descriptors_module);
}
