# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/auth.proto
"""Generated protocol buffer code."""
import ctypes, importlib, sys
_dlopenflags = sys.getdlopenflags()
sys.setdlopenflags(_dlopenflags | ctypes.RTLD_GLOBAL)

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

importlib.import_module('_descriptors')
sys.setdlopenflags(_dlopenflags)
del _dlopenflags, ctypes, importlib, sys
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/api/auth.proto',
  package='google.api',
  syntax='proto3',
  serialized_options=b'\n\016com.google.apiB\tAuthProtoP\001ZEgoogle.golang.org/genproto/googleapis/api/serviceconfig;serviceconfig\242\002\004GAPI',
  create_key=_descriptor._internal_create_key,
  serialized_pb=''
)



Authentication = _reflection.GeneratedProtocolMessageType('Authentication', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.Authentication',
  '__module__' : 'google.api.auth_pb2'
  # @@protoc_insertion_point(class_scope:google.api.Authentication)
  })
_sym_db.RegisterMessage(Authentication)

AuthenticationRule = _reflection.GeneratedProtocolMessageType('AuthenticationRule', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.AuthenticationRule',
  '__module__' : 'google.api.auth_pb2'
  # @@protoc_insertion_point(class_scope:google.api.AuthenticationRule)
  })
_sym_db.RegisterMessage(AuthenticationRule)

AuthProvider = _reflection.GeneratedProtocolMessageType('AuthProvider', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.AuthProvider',
  '__module__' : 'google.api.auth_pb2'
  # @@protoc_insertion_point(class_scope:google.api.AuthProvider)
  })
_sym_db.RegisterMessage(AuthProvider)

OAuthRequirements = _reflection.GeneratedProtocolMessageType('OAuthRequirements', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.OAuthRequirements',
  '__module__' : 'google.api.auth_pb2'
  # @@protoc_insertion_point(class_scope:google.api.OAuthRequirements)
  })
_sym_db.RegisterMessage(OAuthRequirements)

AuthRequirement = _reflection.GeneratedProtocolMessageType('AuthRequirement', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.AuthRequirement',
  '__module__' : 'google.api.auth_pb2'
  # @@protoc_insertion_point(class_scope:google.api.AuthRequirement)
  })
_sym_db.RegisterMessage(AuthRequirement)

# @@protoc_insertion_point(module_scope)
