# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/config_change.proto
"""Generated protocol buffer code."""
import ctypes, importlib, sys
_dlopenflags = sys.getdlopenflags()
sys.setdlopenflags(_dlopenflags | ctypes.RTLD_GLOBAL)

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

importlib.import_module('_descriptors')
sys.setdlopenflags(_dlopenflags)
del _dlopenflags, ctypes, importlib, sys
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/api/config_change.proto',
  package='google.api',
  syntax='proto3',
  serialized_options=b'\n\016com.google.apiB\021ConfigChangeProtoP\001ZCgoogle.golang.org/genproto/googleapis/api/configchange;configchange\242\002\004GAPI',
  create_key=_descriptor._internal_create_key,
  serialized_pb=''
)

_CHANGETYPE = _descriptor.EnumDescriptor(
  name='ChangeType',
  full_name='google.api.ChangeType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=231,
  serialized_end=310,
)

ChangeType = enum_type_wrapper.EnumTypeWrapper(_CHANGETYPE)
CHANGE_TYPE_UNSPECIFIED = 0
ADDED = 1
REMOVED = 2
MODIFIED = 3


ConfigChange = _reflection.GeneratedProtocolMessageType('ConfigChange', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.ConfigChange',
  '__module__' : 'google.api.config_change_pb2'
  # @@protoc_insertion_point(class_scope:google.api.ConfigChange)
  })
_sym_db.RegisterMessage(ConfigChange)

Advice = _reflection.GeneratedProtocolMessageType('Advice', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.Advice',
  '__module__' : 'google.api.config_change_pb2'
  # @@protoc_insertion_point(class_scope:google.api.Advice)
  })
_sym_db.RegisterMessage(Advice)

# @@protoc_insertion_point(module_scope)
