# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/distribution.proto
"""Generated protocol buffer code."""
import ctypes, importlib, sys
_dlopenflags = sys.getdlopenflags()
sys.setdlopenflags(_dlopenflags | ctypes.RTLD_GLOBAL)

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

importlib.import_module('_descriptors')
sys.setdlopenflags(_dlopenflags)
del _dlopenflags, ctypes, importlib, sys
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/api/distribution.proto',
  package='google.api',
  syntax='proto3',
  serialized_options=b'\n\016com.google.apiB\021DistributionProtoP\001ZCgoogle.golang.org/genproto/googleapis/api/distribution;distribution\242\002\004GAPI',
  create_key=_descriptor._internal_create_key,
  serialized_pb=''
)



Distribution = _reflection.GeneratedProtocolMessageType('Distribution', (_message.Message,), {

  'Range' : _reflection.GeneratedProtocolMessageType('Range', (_message.Message,), {
    'DESCRIPTOR' : 'google.api.Distribution.Range',
    '__module__' : 'google.api.distribution_pb2'
    # @@protoc_insertion_point(class_scope:google.api.Distribution.Range)
    })
  ,

  'BucketOptions' : _reflection.GeneratedProtocolMessageType('BucketOptions', (_message.Message,), {

    'Linear' : _reflection.GeneratedProtocolMessageType('Linear', (_message.Message,), {
      'DESCRIPTOR' : 'google.api.Distribution.BucketOptions.Linear',
      '__module__' : 'google.api.distribution_pb2'
      # @@protoc_insertion_point(class_scope:google.api.Distribution.BucketOptions.Linear)
      })
    ,

    'Exponential' : _reflection.GeneratedProtocolMessageType('Exponential', (_message.Message,), {
      'DESCRIPTOR' : 'google.api.Distribution.BucketOptions.Exponential',
      '__module__' : 'google.api.distribution_pb2'
      # @@protoc_insertion_point(class_scope:google.api.Distribution.BucketOptions.Exponential)
      })
    ,

    'Explicit' : _reflection.GeneratedProtocolMessageType('Explicit', (_message.Message,), {
      'DESCRIPTOR' : 'google.api.Distribution.BucketOptions.Explicit',
      '__module__' : 'google.api.distribution_pb2'
      # @@protoc_insertion_point(class_scope:google.api.Distribution.BucketOptions.Explicit)
      })
    ,
    'DESCRIPTOR' : 'google.api.Distribution.BucketOptions',
    '__module__' : 'google.api.distribution_pb2'
    # @@protoc_insertion_point(class_scope:google.api.Distribution.BucketOptions)
    })
  ,

  'Exemplar' : _reflection.GeneratedProtocolMessageType('Exemplar', (_message.Message,), {
    'DESCRIPTOR' : 'google.api.Distribution.Exemplar',
    '__module__' : 'google.api.distribution_pb2'
    # @@protoc_insertion_point(class_scope:google.api.Distribution.Exemplar)
    })
  ,
  'DESCRIPTOR' : 'google.api.Distribution',
  '__module__' : 'google.api.distribution_pb2'
  # @@protoc_insertion_point(class_scope:google.api.Distribution)
  })
_sym_db.RegisterMessage(Distribution)
_sym_db.RegisterMessage(Distribution.Range)
_sym_db.RegisterMessage(Distribution.BucketOptions)
_sym_db.RegisterMessage(Distribution.BucketOptions.Linear)
_sym_db.RegisterMessage(Distribution.BucketOptions.Exponential)
_sym_db.RegisterMessage(Distribution.BucketOptions.Explicit)
_sym_db.RegisterMessage(Distribution.Exemplar)

# @@protoc_insertion_point(module_scope)
