# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/documentation.proto
"""Generated protocol buffer code."""
import ctypes, importlib, sys
_dlopenflags = sys.getdlopenflags()
sys.setdlopenflags(_dlopenflags | ctypes.RTLD_GLOBAL)

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

importlib.import_module('google.api_common_protos._descriptors')
sys.setdlopenflags(_dlopenflags)
del _dlopenflags, ctypes, importlib, sys
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/api/documentation.proto',
  package='google.api',
  syntax='proto3',
  serialized_options=b'\n\016com.google.apiB\022DocumentationProtoP\001ZEgoogle.golang.org/genproto/googleapis/api/serviceconfig;serviceconfig\242\002\004GAPI',
  create_key=_descriptor._internal_create_key,
  serialized_pb=''
)



Documentation = _reflection.GeneratedProtocolMessageType('Documentation', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.Documentation',
  '__module__' : 'google.api.documentation_pb2'
  # @@protoc_insertion_point(class_scope:google.api.Documentation)
  })
_sym_db.RegisterMessage(Documentation)

DocumentationRule = _reflection.GeneratedProtocolMessageType('DocumentationRule', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.DocumentationRule',
  '__module__' : 'google.api.documentation_pb2'
  # @@protoc_insertion_point(class_scope:google.api.DocumentationRule)
  })
_sym_db.RegisterMessage(DocumentationRule)

Page = _reflection.GeneratedProtocolMessageType('Page', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.Page',
  '__module__' : 'google.api.documentation_pb2'
  # @@protoc_insertion_point(class_scope:google.api.Page)
  })
_sym_db.RegisterMessage(Page)

# @@protoc_insertion_point(module_scope)
