# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/logging.proto
"""Generated protocol buffer code."""
import ctypes, importlib, sys
_dlopenflags = sys.getdlopenflags()
sys.setdlopenflags(_dlopenflags | ctypes.RTLD_GLOBAL)

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

importlib.import_module('_descriptors')
sys.setdlopenflags(_dlopenflags)
del _dlopenflags, ctypes, importlib, sys
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/api/logging.proto',
  package='google.api',
  syntax='proto3',
  serialized_options=b'\n\016com.google.apiB\014LoggingProtoP\001ZEgoogle.golang.org/genproto/googleapis/api/serviceconfig;serviceconfig\242\002\004GAPI',
  create_key=_descriptor._internal_create_key,
  serialized_pb=''
)



Logging = _reflection.GeneratedProtocolMessageType('Logging', (_message.Message,), {

  'LoggingDestination' : _reflection.GeneratedProtocolMessageType('LoggingDestination', (_message.Message,), {
    'DESCRIPTOR' : 'google.api.Logging.LoggingDestination',
    '__module__' : 'google.api.logging_pb2'
    # @@protoc_insertion_point(class_scope:google.api.Logging.LoggingDestination)
    })
  ,
  'DESCRIPTOR' : 'google.api.Logging',
  '__module__' : 'google.api.logging_pb2'
  # @@protoc_insertion_point(class_scope:google.api.Logging)
  })
_sym_db.RegisterMessage(Logging)
_sym_db.RegisterMessage(Logging.LoggingDestination)

# @@protoc_insertion_point(module_scope)
