# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/metric.proto
"""Generated protocol buffer code."""
import ctypes, importlib, sys
_dlopenflags = sys.getdlopenflags()
sys.setdlopenflags(_dlopenflags | ctypes.RTLD_GLOBAL)

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

importlib.import_module('google.api_common_protos._descriptors')
sys.setdlopenflags(_dlopenflags)
del _dlopenflags, ctypes, importlib, sys
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/api/metric.proto',
  package='google.api',
  syntax='proto3',
  serialized_options=b'\n\016com.google.apiB\013MetricProtoP\001Z7google.golang.org/genproto/googleapis/api/metric;metric\242\002\004GAPI',
  create_key=_descriptor._internal_create_key,
  serialized_pb=''
)



MetricDescriptor = _reflection.GeneratedProtocolMessageType('MetricDescriptor', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.MetricDescriptor',
  '__module__' : 'google.api.metric_pb2'
  # @@protoc_insertion_point(class_scope:google.api.MetricDescriptor)
  })
_sym_db.RegisterMessage(MetricDescriptor)

Metric = _reflection.GeneratedProtocolMessageType('Metric', (_message.Message,), {

  'LabelsEntry' : _reflection.GeneratedProtocolMessageType('LabelsEntry', (_message.Message,), {
    'DESCRIPTOR' : 'google.api.Metric.LabelsEntry',
    '__module__' : 'google.api.metric_pb2'
    # @@protoc_insertion_point(class_scope:google.api.Metric.LabelsEntry)
    })
  ,
  'DESCRIPTOR' : 'google.api.Metric',
  '__module__' : 'google.api.metric_pb2'
  # @@protoc_insertion_point(class_scope:google.api.Metric)
  })
_sym_db.RegisterMessage(Metric)
_sym_db.RegisterMessage(Metric.LabelsEntry)

# @@protoc_insertion_point(module_scope)
