# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/monitored_resource.proto
"""Generated protocol buffer code."""
import ctypes, importlib, sys
_dlopenflags = sys.getdlopenflags()
sys.setdlopenflags(_dlopenflags | ctypes.RTLD_GLOBAL)

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

importlib.import_module('_descriptors')
sys.setdlopenflags(_dlopenflags)
del _dlopenflags, ctypes, importlib, sys
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/api/monitored_resource.proto',
  package='google.api',
  syntax='proto3',
  serialized_options=b'\n\016com.google.apiB\026MonitoredResourceProtoP\001ZCgoogle.golang.org/genproto/googleapis/api/monitoredres;monitoredres\370\001\001\242\002\004GAPI',
  create_key=_descriptor._internal_create_key,
  serialized_pb=''
)



MonitoredResourceDescriptor = _reflection.GeneratedProtocolMessageType('MonitoredResourceDescriptor', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.MonitoredResourceDescriptor',
  '__module__' : 'google.api.monitored_resource_pb2'
  # @@protoc_insertion_point(class_scope:google.api.MonitoredResourceDescriptor)
  })
_sym_db.RegisterMessage(MonitoredResourceDescriptor)

MonitoredResource = _reflection.GeneratedProtocolMessageType('MonitoredResource', (_message.Message,), {

  'LabelsEntry' : _reflection.GeneratedProtocolMessageType('LabelsEntry', (_message.Message,), {
    'DESCRIPTOR' : 'google.api.MonitoredResource.LabelsEntry',
    '__module__' : 'google.api.monitored_resource_pb2'
    # @@protoc_insertion_point(class_scope:google.api.MonitoredResource.LabelsEntry)
    })
  ,
  'DESCRIPTOR' : 'google.api.MonitoredResource',
  '__module__' : 'google.api.monitored_resource_pb2'
  # @@protoc_insertion_point(class_scope:google.api.MonitoredResource)
  })
_sym_db.RegisterMessage(MonitoredResource)
_sym_db.RegisterMessage(MonitoredResource.LabelsEntry)

MonitoredResourceMetadata = _reflection.GeneratedProtocolMessageType('MonitoredResourceMetadata', (_message.Message,), {

  'UserLabelsEntry' : _reflection.GeneratedProtocolMessageType('UserLabelsEntry', (_message.Message,), {
    'DESCRIPTOR' : 'google.api.MonitoredResourceMetadata.UserLabelsEntry',
    '__module__' : 'google.api.monitored_resource_pb2'
    # @@protoc_insertion_point(class_scope:google.api.MonitoredResourceMetadata.UserLabelsEntry)
    })
  ,
  'DESCRIPTOR' : 'google.api.MonitoredResourceMetadata',
  '__module__' : 'google.api.monitored_resource_pb2'
  # @@protoc_insertion_point(class_scope:google.api.MonitoredResourceMetadata)
  })
_sym_db.RegisterMessage(MonitoredResourceMetadata)
_sym_db.RegisterMessage(MonitoredResourceMetadata.UserLabelsEntry)

# @@protoc_insertion_point(module_scope)
