# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/source_info.proto
"""Generated protocol buffer code."""
import ctypes, importlib, sys
_dlopenflags = sys.getdlopenflags()
sys.setdlopenflags(_dlopenflags | ctypes.RTLD_GLOBAL)

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

importlib.import_module('google.api_common_protos._descriptors')
sys.setdlopenflags(_dlopenflags)
del _dlopenflags, ctypes, importlib, sys
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/api/source_info.proto',
  package='google.api',
  syntax='proto3',
  serialized_options=b'\n\016com.google.apiB\017SourceInfoProtoP\001ZEgoogle.golang.org/genproto/googleapis/api/serviceconfig;serviceconfig\242\002\004GAPI',
  create_key=_descriptor._internal_create_key,
  serialized_pb=''
)



SourceInfo = _reflection.GeneratedProtocolMessageType('SourceInfo', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.SourceInfo',
  '__module__' : 'google.api.source_info_pb2'
  # @@protoc_insertion_point(class_scope:google.api.SourceInfo)
  })
_sym_db.RegisterMessage(SourceInfo)

# @@protoc_insertion_point(module_scope)
