# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/system_parameter.proto
"""Generated protocol buffer code."""
import ctypes, importlib, sys
_dlopenflags = sys.getdlopenflags()
sys.setdlopenflags(_dlopenflags | ctypes.RTLD_GLOBAL)

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

importlib.import_module('google.api_common_protos._descriptors')
sys.setdlopenflags(_dlopenflags)
del _dlopenflags, ctypes, importlib, sys
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/api/system_parameter.proto',
  package='google.api',
  syntax='proto3',
  serialized_options=b'\n\016com.google.apiB\024SystemParameterProtoP\001ZEgoogle.golang.org/genproto/googleapis/api/serviceconfig;serviceconfig\242\002\004GAPI',
  create_key=_descriptor._internal_create_key,
  serialized_pb=''
)



SystemParameters = _reflection.GeneratedProtocolMessageType('SystemParameters', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.SystemParameters',
  '__module__' : 'google.api.system_parameter_pb2'
  # @@protoc_insertion_point(class_scope:google.api.SystemParameters)
  })
_sym_db.RegisterMessage(SystemParameters)

SystemParameterRule = _reflection.GeneratedProtocolMessageType('SystemParameterRule', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.SystemParameterRule',
  '__module__' : 'google.api.system_parameter_pb2'
  # @@protoc_insertion_point(class_scope:google.api.SystemParameterRule)
  })
_sym_db.RegisterMessage(SystemParameterRule)

SystemParameter = _reflection.GeneratedProtocolMessageType('SystemParameter', (_message.Message,), {
  'DESCRIPTOR' : 'google.api.SystemParameter',
  '__module__' : 'google.api.system_parameter_pb2'
  # @@protoc_insertion_point(class_scope:google.api.SystemParameter)
  })
_sym_db.RegisterMessage(SystemParameter)

# @@protoc_insertion_point(module_scope)
