# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/type/datetime.proto
"""Generated protocol buffer code."""
import ctypes, importlib, sys
_dlopenflags = sys.getdlopenflags()
sys.setdlopenflags(_dlopenflags | ctypes.RTLD_GLOBAL)

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

importlib.import_module('google.api_common_protos._descriptors')
sys.setdlopenflags(_dlopenflags)
del _dlopenflags, ctypes, importlib, sys
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/type/datetime.proto',
  package='google.type',
  syntax='proto3',
  serialized_options=b'\n\017com.google.typeB\rDateTimeProtoP\001Z<google.golang.org/genproto/googleapis/type/datetime;datetime\370\001\001\242\002\003GTP',
  create_key=_descriptor._internal_create_key,
  serialized_pb=''
)



DateTime = _reflection.GeneratedProtocolMessageType('DateTime', (_message.Message,), {
  'DESCRIPTOR' : 'google.type.DateTime',
  '__module__' : 'google.type.datetime_pb2'
  # @@protoc_insertion_point(class_scope:google.type.DateTime)
  })
_sym_db.RegisterMessage(DateTime)

TimeZone = _reflection.GeneratedProtocolMessageType('TimeZone', (_message.Message,), {
  'DESCRIPTOR' : 'google.type.TimeZone',
  '__module__' : 'google.type.datetime_pb2'
  # @@protoc_insertion_point(class_scope:google.type.TimeZone)
  })
_sym_db.RegisterMessage(TimeZone)

# @@protoc_insertion_point(module_scope)
