# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/type/postal_address.proto
"""Generated protocol buffer code."""
import ctypes, importlib, sys
_dlopenflags = sys.getdlopenflags()
sys.setdlopenflags(_dlopenflags | ctypes.RTLD_GLOBAL)

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

importlib.import_module('google.api_common_protos._descriptors')
sys.setdlopenflags(_dlopenflags)
del _dlopenflags, ctypes, importlib, sys
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/type/postal_address.proto',
  package='google.type',
  syntax='proto3',
  serialized_options=b'\n\017com.google.typeB\022PostalAddressProtoP\001ZFgoogle.golang.org/genproto/googleapis/type/postaladdress;postaladdress\370\001\001\242\002\003GTP',
  create_key=_descriptor._internal_create_key,
  serialized_pb=''
)



PostalAddress = _reflection.GeneratedProtocolMessageType('PostalAddress', (_message.Message,), {
  'DESCRIPTOR' : 'google.type.PostalAddress',
  '__module__' : 'google.type.postal_address_pb2'
  # @@protoc_insertion_point(class_scope:google.type.PostalAddress)
  })
_sym_db.RegisterMessage(PostalAddress)

# @@protoc_insertion_point(module_scope)
